<?php
/**
 * AttemptTrigger
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hookdeck\Model;
use \Hookdeck\ObjectSerializer;

/**
 * AttemptTrigger Class Doc Comment
 *
 * @category Class
 * @description How the attempt was triggered
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AttemptTrigger
{
    /**
     * Possible values of this enum
     */
    public const INITIAL = 'INITIAL';

    public const MANUAL = 'MANUAL';

    public const BULK_RETRY = 'BULK_RETRY';

    public const UNPAUSE = 'UNPAUSE';

    public const AUTOMATIC = 'AUTOMATIC';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INITIAL,
            self::MANUAL,
            self::BULK_RETRY,
            self::UNPAUSE,
            self::AUTOMATIC
        ];
    }
}


