<?php
/**
 * IgnoredEventCause
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hookdeck\Model;
use \Hookdeck\ObjectSerializer;

/**
 * IgnoredEventCause Class Doc Comment
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IgnoredEventCause
{
    /**
     * Possible values of this enum
     */
    public const DISABLED = 'DISABLED';

    public const FILTERED = 'FILTERED';

    public const TRANSFORMATION_FAILED = 'TRANSFORMATION_FAILED';

    public const CLI_DISCONNECTED = 'CLI_DISCONNECTED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DISABLED,
            self::FILTERED,
            self::TRANSFORMATION_FAILED,
            self::CLI_DISCONNECTED
        ];
    }
}


