<?php
/**
 * IssueStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hookdeck\Model;
use \Hookdeck\ObjectSerializer;

/**
 * IssueStatus Class Doc Comment
 *
 * @category Class
 * @description Issue status
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IssueStatus
{
    /**
     * Possible values of this enum
     */
    public const OPENED = 'OPENED';

    public const IGNORED = 'IGNORED';

    public const ACKNOWLEDGED = 'ACKNOWLEDGED';

    public const RESOLVED = 'RESOLVED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OPENED,
            self::IGNORED,
            self::ACKNOWLEDGED,
            self::RESOLVED
        ];
    }
}


