<?php
/**
 * RequestRejectionCause
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hookdeck\Model;
use \Hookdeck\ObjectSerializer;

/**
 * RequestRejectionCause Class Doc Comment
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RequestRejectionCause
{
    /**
     * Possible values of this enum
     */
    public const SOURCE_DISABLED = 'SOURCE_DISABLED';

    public const NO_CONNECTION = 'NO_CONNECTION';

    public const VERIFICATION_FAILED = 'VERIFICATION_FAILED';

    public const UNSUPPORTED_HTTP_METHOD = 'UNSUPPORTED_HTTP_METHOD';

    public const UNSUPPORTED_CONTENT_TYPE = 'UNSUPPORTED_CONTENT_TYPE';

    public const UNPARSABLE_JSON = 'UNPARSABLE_JSON';

    public const PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE';

    public const INGESTION_FATAL = 'INGESTION_FATAL';

    public const UNKNOWN = 'UNKNOWN';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SOURCE_DISABLED,
            self::NO_CONNECTION,
            self::VERIFICATION_FAILED,
            self::UNSUPPORTED_HTTP_METHOD,
            self::UNSUPPORTED_CONTENT_TYPE,
            self::UNPARSABLE_JSON,
            self::PAYLOAD_TOO_LARGE,
            self::INGESTION_FATAL,
            self::UNKNOWN
        ];
    }
}


