<?php
/**
 * Request
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hookdeck\Model;

use \ArrayAccess;
use \Hookdeck\ObjectSerializer;

/**
 * Request Class Doc Comment
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Request implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'team_id' => 'string',
        'verified' => 'bool',
        'original_event_data_id' => 'string',
        'rejection_cause' => '\Hookdeck\Model\RequestRejectionCause',
        'ingest_priority' => 'string',
        'ingested_at' => '\DateTime',
        'source_id' => 'string',
        'events_count' => 'int',
        'cli_events_count' => 'int',
        'ignored_count' => 'int',
        'updated_at' => '\DateTime',
        'created_at' => '\DateTime',
        'data' => '\Hookdeck\Model\ShortEventData'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'team_id' => null,
        'verified' => null,
        'original_event_data_id' => null,
        'rejection_cause' => null,
        'ingest_priority' => null,
        'ingested_at' => 'date-time',
        'source_id' => null,
        'events_count' => null,
        'cli_events_count' => null,
        'ignored_count' => null,
        'updated_at' => 'date-time',
        'created_at' => 'date-time',
        'data' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'team_id' => false,
        'verified' => true,
        'original_event_data_id' => true,
        'rejection_cause' => false,
        'ingest_priority' => true,
        'ingested_at' => true,
        'source_id' => false,
        'events_count' => true,
        'cli_events_count' => true,
        'ignored_count' => true,
        'updated_at' => false,
        'created_at' => false,
        'data' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'team_id' => 'team_id',
        'verified' => 'verified',
        'original_event_data_id' => 'original_event_data_id',
        'rejection_cause' => 'rejection_cause',
        'ingest_priority' => 'ingest_priority',
        'ingested_at' => 'ingested_at',
        'source_id' => 'source_id',
        'events_count' => 'events_count',
        'cli_events_count' => 'cli_events_count',
        'ignored_count' => 'ignored_count',
        'updated_at' => 'updated_at',
        'created_at' => 'created_at',
        'data' => 'data'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'team_id' => 'setTeamId',
        'verified' => 'setVerified',
        'original_event_data_id' => 'setOriginalEventDataId',
        'rejection_cause' => 'setRejectionCause',
        'ingest_priority' => 'setIngestPriority',
        'ingested_at' => 'setIngestedAt',
        'source_id' => 'setSourceId',
        'events_count' => 'setEventsCount',
        'cli_events_count' => 'setCliEventsCount',
        'ignored_count' => 'setIgnoredCount',
        'updated_at' => 'setUpdatedAt',
        'created_at' => 'setCreatedAt',
        'data' => 'setData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'team_id' => 'getTeamId',
        'verified' => 'getVerified',
        'original_event_data_id' => 'getOriginalEventDataId',
        'rejection_cause' => 'getRejectionCause',
        'ingest_priority' => 'getIngestPriority',
        'ingested_at' => 'getIngestedAt',
        'source_id' => 'getSourceId',
        'events_count' => 'getEventsCount',
        'cli_events_count' => 'getCliEventsCount',
        'ignored_count' => 'getIgnoredCount',
        'updated_at' => 'getUpdatedAt',
        'created_at' => 'getCreatedAt',
        'data' => 'getData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const INGEST_PRIORITY_NORMAL = 'NORMAL';
    public const INGEST_PRIORITY_LOW = 'LOW';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIngestPriorityAllowableValues()
    {
        return [
            self::INGEST_PRIORITY_NORMAL,
            self::INGEST_PRIORITY_LOW,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('team_id', $data ?? [], null);
        $this->setIfExists('verified', $data ?? [], null);
        $this->setIfExists('original_event_data_id', $data ?? [], null);
        $this->setIfExists('rejection_cause', $data ?? [], null);
        $this->setIfExists('ingest_priority', $data ?? [], null);
        $this->setIfExists('ingested_at', $data ?? [], null);
        $this->setIfExists('source_id', $data ?? [], null);
        $this->setIfExists('events_count', $data ?? [], null);
        $this->setIfExists('cli_events_count', $data ?? [], null);
        $this->setIfExists('ignored_count', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('data', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['team_id'] === null) {
            $invalidProperties[] = "'team_id' can't be null";
        }
        if ($this->container['verified'] === null) {
            $invalidProperties[] = "'verified' can't be null";
        }
        if ($this->container['original_event_data_id'] === null) {
            $invalidProperties[] = "'original_event_data_id' can't be null";
        }
        if ($this->container['rejection_cause'] === null) {
            $invalidProperties[] = "'rejection_cause' can't be null";
        }
        if ($this->container['ingest_priority'] === null) {
            $invalidProperties[] = "'ingest_priority' can't be null";
        }
        $allowedValues = $this->getIngestPriorityAllowableValues();
        if (!is_null($this->container['ingest_priority']) && !in_array($this->container['ingest_priority'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'ingest_priority', must be one of '%s'",
                $this->container['ingest_priority'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['ingested_at'] === null) {
            $invalidProperties[] = "'ingested_at' can't be null";
        }
        if ($this->container['source_id'] === null) {
            $invalidProperties[] = "'source_id' can't be null";
        }
        if ($this->container['events_count'] === null) {
            $invalidProperties[] = "'events_count' can't be null";
        }
        if ($this->container['cli_events_count'] === null) {
            $invalidProperties[] = "'cli_events_count' can't be null";
        }
        if ($this->container['ignored_count'] === null) {
            $invalidProperties[] = "'ignored_count' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id ID of the request
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets team_id
     *
     * @return string
     */
    public function getTeamId()
    {
        return $this->container['team_id'];
    }

    /**
     * Sets team_id
     *
     * @param string $team_id ID of the project
     *
     * @return self
     */
    public function setTeamId($team_id)
    {
        if (is_null($team_id)) {
            throw new \InvalidArgumentException('non-nullable team_id cannot be null');
        }
        $this->container['team_id'] = $team_id;

        return $this;
    }

    /**
     * Gets verified
     *
     * @return bool
     */
    public function getVerified()
    {
        return $this->container['verified'];
    }

    /**
     * Sets verified
     *
     * @param bool $verified Whether or not the request was verified when received
     *
     * @return self
     */
    public function setVerified($verified)
    {
        if (is_null($verified)) {
            array_push($this->openAPINullablesSetToNull, 'verified');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('verified', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['verified'] = $verified;

        return $this;
    }

    /**
     * Gets original_event_data_id
     *
     * @return string
     */
    public function getOriginalEventDataId()
    {
        return $this->container['original_event_data_id'];
    }

    /**
     * Sets original_event_data_id
     *
     * @param string $original_event_data_id ID of the request data
     *
     * @return self
     */
    public function setOriginalEventDataId($original_event_data_id)
    {
        if (is_null($original_event_data_id)) {
            array_push($this->openAPINullablesSetToNull, 'original_event_data_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('original_event_data_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['original_event_data_id'] = $original_event_data_id;

        return $this;
    }

    /**
     * Gets rejection_cause
     *
     * @return \Hookdeck\Model\RequestRejectionCause
     */
    public function getRejectionCause()
    {
        return $this->container['rejection_cause'];
    }

    /**
     * Sets rejection_cause
     *
     * @param \Hookdeck\Model\RequestRejectionCause $rejection_cause rejection_cause
     *
     * @return self
     */
    public function setRejectionCause($rejection_cause)
    {
        if (is_null($rejection_cause)) {
            throw new \InvalidArgumentException('non-nullable rejection_cause cannot be null');
        }
        $this->container['rejection_cause'] = $rejection_cause;

        return $this;
    }

    /**
     * Gets ingest_priority
     *
     * @return string
     */
    public function getIngestPriority()
    {
        return $this->container['ingest_priority'];
    }

    /**
     * Sets ingest_priority
     *
     * @param string $ingest_priority The priority attributed to the request when received
     *
     * @return self
     */
    public function setIngestPriority($ingest_priority)
    {
        if (is_null($ingest_priority)) {
            array_push($this->openAPINullablesSetToNull, 'ingest_priority');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ingest_priority', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getIngestPriorityAllowableValues();
        if (!is_null($ingest_priority) && !in_array($ingest_priority, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'ingest_priority', must be one of '%s'",
                    $ingest_priority,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['ingest_priority'] = $ingest_priority;

        return $this;
    }

    /**
     * Gets ingested_at
     *
     * @return \DateTime
     */
    public function getIngestedAt()
    {
        return $this->container['ingested_at'];
    }

    /**
     * Sets ingested_at
     *
     * @param \DateTime $ingested_at The time the request was originally received
     *
     * @return self
     */
    public function setIngestedAt($ingested_at)
    {
        if (is_null($ingested_at)) {
            array_push($this->openAPINullablesSetToNull, 'ingested_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ingested_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ingested_at'] = $ingested_at;

        return $this;
    }

    /**
     * Gets source_id
     *
     * @return string
     */
    public function getSourceId()
    {
        return $this->container['source_id'];
    }

    /**
     * Sets source_id
     *
     * @param string $source_id ID of the associated source
     *
     * @return self
     */
    public function setSourceId($source_id)
    {
        if (is_null($source_id)) {
            throw new \InvalidArgumentException('non-nullable source_id cannot be null');
        }
        $this->container['source_id'] = $source_id;

        return $this;
    }

    /**
     * Gets events_count
     *
     * @return int
     */
    public function getEventsCount()
    {
        return $this->container['events_count'];
    }

    /**
     * Sets events_count
     *
     * @param int $events_count The count of events created from this request (CLI events not included)
     *
     * @return self
     */
    public function setEventsCount($events_count)
    {
        if (is_null($events_count)) {
            array_push($this->openAPINullablesSetToNull, 'events_count');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('events_count', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['events_count'] = $events_count;

        return $this;
    }

    /**
     * Gets cli_events_count
     *
     * @return int
     */
    public function getCliEventsCount()
    {
        return $this->container['cli_events_count'];
    }

    /**
     * Sets cli_events_count
     *
     * @param int $cli_events_count The count of CLI events created from this request
     *
     * @return self
     */
    public function setCliEventsCount($cli_events_count)
    {
        if (is_null($cli_events_count)) {
            array_push($this->openAPINullablesSetToNull, 'cli_events_count');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cli_events_count', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cli_events_count'] = $cli_events_count;

        return $this;
    }

    /**
     * Gets ignored_count
     *
     * @return int
     */
    public function getIgnoredCount()
    {
        return $this->container['ignored_count'];
    }

    /**
     * Sets ignored_count
     *
     * @param int $ignored_count ignored_count
     *
     * @return self
     */
    public function setIgnoredCount($ignored_count)
    {
        if (is_null($ignored_count)) {
            array_push($this->openAPINullablesSetToNull, 'ignored_count');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ignored_count', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ignored_count'] = $ignored_count;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at Date the event was last updated
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at Date the event was created
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets data
     *
     * @return \Hookdeck\Model\ShortEventData|null
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param \Hookdeck\Model\ShortEventData|null $data data
     *
     * @return self
     */
    public function setData($data)
    {
        if (is_null($data)) {
            array_push($this->openAPINullablesSetToNull, 'data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data'] = $data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


