<?php
/**
 * TransformationExecution
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hookdeck\Model;

use \ArrayAccess;
use \Hookdeck\ObjectSerializer;

/**
 * TransformationExecution Class Doc Comment
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TransformationExecution implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TransformationExecution';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'transformed_event_data_id' => 'string',
        'original_event_data_id' => 'string',
        'transformation_id' => 'string',
        'team_id' => 'string',
        'webhook_id' => 'string',
        'log_level' => '\Hookdeck\Model\TransformationExecutionLogLevel',
        'logs' => '\Hookdeck\Model\ConsoleLine[]',
        'updated_at' => '\DateTime',
        'created_at' => '\DateTime',
        'original_event_data' => '\Hookdeck\Model\ShortEventData',
        'transformed_event_data' => '\Hookdeck\Model\ShortEventData',
        'issue_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'transformed_event_data_id' => null,
        'original_event_data_id' => null,
        'transformation_id' => null,
        'team_id' => null,
        'webhook_id' => null,
        'log_level' => null,
        'logs' => null,
        'updated_at' => 'date-time',
        'created_at' => 'date-time',
        'original_event_data' => null,
        'transformed_event_data' => null,
        'issue_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'transformed_event_data_id' => false,
        'original_event_data_id' => false,
        'transformation_id' => false,
        'team_id' => false,
        'webhook_id' => false,
        'log_level' => false,
        'logs' => false,
        'updated_at' => false,
        'created_at' => false,
        'original_event_data' => true,
        'transformed_event_data' => true,
        'issue_id' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'transformed_event_data_id' => 'transformed_event_data_id',
        'original_event_data_id' => 'original_event_data_id',
        'transformation_id' => 'transformation_id',
        'team_id' => 'team_id',
        'webhook_id' => 'webhook_id',
        'log_level' => 'log_level',
        'logs' => 'logs',
        'updated_at' => 'updated_at',
        'created_at' => 'created_at',
        'original_event_data' => 'original_event_data',
        'transformed_event_data' => 'transformed_event_data',
        'issue_id' => 'issue_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'transformed_event_data_id' => 'setTransformedEventDataId',
        'original_event_data_id' => 'setOriginalEventDataId',
        'transformation_id' => 'setTransformationId',
        'team_id' => 'setTeamId',
        'webhook_id' => 'setWebhookId',
        'log_level' => 'setLogLevel',
        'logs' => 'setLogs',
        'updated_at' => 'setUpdatedAt',
        'created_at' => 'setCreatedAt',
        'original_event_data' => 'setOriginalEventData',
        'transformed_event_data' => 'setTransformedEventData',
        'issue_id' => 'setIssueId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'transformed_event_data_id' => 'getTransformedEventDataId',
        'original_event_data_id' => 'getOriginalEventDataId',
        'transformation_id' => 'getTransformationId',
        'team_id' => 'getTeamId',
        'webhook_id' => 'getWebhookId',
        'log_level' => 'getLogLevel',
        'logs' => 'getLogs',
        'updated_at' => 'getUpdatedAt',
        'created_at' => 'getCreatedAt',
        'original_event_data' => 'getOriginalEventData',
        'transformed_event_data' => 'getTransformedEventData',
        'issue_id' => 'getIssueId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('transformed_event_data_id', $data ?? [], null);
        $this->setIfExists('original_event_data_id', $data ?? [], null);
        $this->setIfExists('transformation_id', $data ?? [], null);
        $this->setIfExists('team_id', $data ?? [], null);
        $this->setIfExists('webhook_id', $data ?? [], null);
        $this->setIfExists('log_level', $data ?? [], null);
        $this->setIfExists('logs', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('original_event_data', $data ?? [], null);
        $this->setIfExists('transformed_event_data', $data ?? [], null);
        $this->setIfExists('issue_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['transformed_event_data_id'] === null) {
            $invalidProperties[] = "'transformed_event_data_id' can't be null";
        }
        if ($this->container['original_event_data_id'] === null) {
            $invalidProperties[] = "'original_event_data_id' can't be null";
        }
        if ($this->container['transformation_id'] === null) {
            $invalidProperties[] = "'transformation_id' can't be null";
        }
        if ($this->container['team_id'] === null) {
            $invalidProperties[] = "'team_id' can't be null";
        }
        if ($this->container['webhook_id'] === null) {
            $invalidProperties[] = "'webhook_id' can't be null";
        }
        if ($this->container['log_level'] === null) {
            $invalidProperties[] = "'log_level' can't be null";
        }
        if ($this->container['logs'] === null) {
            $invalidProperties[] = "'logs' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets transformed_event_data_id
     *
     * @return string
     */
    public function getTransformedEventDataId()
    {
        return $this->container['transformed_event_data_id'];
    }

    /**
     * Sets transformed_event_data_id
     *
     * @param string $transformed_event_data_id transformed_event_data_id
     *
     * @return self
     */
    public function setTransformedEventDataId($transformed_event_data_id)
    {
        if (is_null($transformed_event_data_id)) {
            throw new \InvalidArgumentException('non-nullable transformed_event_data_id cannot be null');
        }
        $this->container['transformed_event_data_id'] = $transformed_event_data_id;

        return $this;
    }

    /**
     * Gets original_event_data_id
     *
     * @return string
     */
    public function getOriginalEventDataId()
    {
        return $this->container['original_event_data_id'];
    }

    /**
     * Sets original_event_data_id
     *
     * @param string $original_event_data_id original_event_data_id
     *
     * @return self
     */
    public function setOriginalEventDataId($original_event_data_id)
    {
        if (is_null($original_event_data_id)) {
            throw new \InvalidArgumentException('non-nullable original_event_data_id cannot be null');
        }
        $this->container['original_event_data_id'] = $original_event_data_id;

        return $this;
    }

    /**
     * Gets transformation_id
     *
     * @return string
     */
    public function getTransformationId()
    {
        return $this->container['transformation_id'];
    }

    /**
     * Sets transformation_id
     *
     * @param string $transformation_id transformation_id
     *
     * @return self
     */
    public function setTransformationId($transformation_id)
    {
        if (is_null($transformation_id)) {
            throw new \InvalidArgumentException('non-nullable transformation_id cannot be null');
        }
        $this->container['transformation_id'] = $transformation_id;

        return $this;
    }

    /**
     * Gets team_id
     *
     * @return string
     */
    public function getTeamId()
    {
        return $this->container['team_id'];
    }

    /**
     * Sets team_id
     *
     * @param string $team_id ID of the project
     *
     * @return self
     */
    public function setTeamId($team_id)
    {
        if (is_null($team_id)) {
            throw new \InvalidArgumentException('non-nullable team_id cannot be null');
        }
        $this->container['team_id'] = $team_id;

        return $this;
    }

    /**
     * Gets webhook_id
     *
     * @return string
     */
    public function getWebhookId()
    {
        return $this->container['webhook_id'];
    }

    /**
     * Sets webhook_id
     *
     * @param string $webhook_id webhook_id
     *
     * @return self
     */
    public function setWebhookId($webhook_id)
    {
        if (is_null($webhook_id)) {
            throw new \InvalidArgumentException('non-nullable webhook_id cannot be null');
        }
        $this->container['webhook_id'] = $webhook_id;

        return $this;
    }

    /**
     * Gets log_level
     *
     * @return \Hookdeck\Model\TransformationExecutionLogLevel
     */
    public function getLogLevel()
    {
        return $this->container['log_level'];
    }

    /**
     * Sets log_level
     *
     * @param \Hookdeck\Model\TransformationExecutionLogLevel $log_level log_level
     *
     * @return self
     */
    public function setLogLevel($log_level)
    {
        if (is_null($log_level)) {
            throw new \InvalidArgumentException('non-nullable log_level cannot be null');
        }
        $this->container['log_level'] = $log_level;

        return $this;
    }

    /**
     * Gets logs
     *
     * @return \Hookdeck\Model\ConsoleLine[]
     */
    public function getLogs()
    {
        return $this->container['logs'];
    }

    /**
     * Sets logs
     *
     * @param \Hookdeck\Model\ConsoleLine[] $logs logs
     *
     * @return self
     */
    public function setLogs($logs)
    {
        if (is_null($logs)) {
            throw new \InvalidArgumentException('non-nullable logs cannot be null');
        }
        $this->container['logs'] = $logs;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets original_event_data
     *
     * @return \Hookdeck\Model\ShortEventData|null
     */
    public function getOriginalEventData()
    {
        return $this->container['original_event_data'];
    }

    /**
     * Sets original_event_data
     *
     * @param \Hookdeck\Model\ShortEventData|null $original_event_data original_event_data
     *
     * @return self
     */
    public function setOriginalEventData($original_event_data)
    {
        if (is_null($original_event_data)) {
            array_push($this->openAPINullablesSetToNull, 'original_event_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('original_event_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['original_event_data'] = $original_event_data;

        return $this;
    }

    /**
     * Gets transformed_event_data
     *
     * @return \Hookdeck\Model\ShortEventData|null
     */
    public function getTransformedEventData()
    {
        return $this->container['transformed_event_data'];
    }

    /**
     * Sets transformed_event_data
     *
     * @param \Hookdeck\Model\ShortEventData|null $transformed_event_data transformed_event_data
     *
     * @return self
     */
    public function setTransformedEventData($transformed_event_data)
    {
        if (is_null($transformed_event_data)) {
            array_push($this->openAPINullablesSetToNull, 'transformed_event_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('transformed_event_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['transformed_event_data'] = $transformed_event_data;

        return $this;
    }

    /**
     * Gets issue_id
     *
     * @return string|null
     */
    public function getIssueId()
    {
        return $this->container['issue_id'];
    }

    /**
     * Sets issue_id
     *
     * @param string|null $issue_id issue_id
     *
     * @return self
     */
    public function setIssueId($issue_id)
    {
        if (is_null($issue_id)) {
            array_push($this->openAPINullablesSetToNull, 'issue_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('issue_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['issue_id'] = $issue_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


