<?php
/**
 * BulkRetryRequestsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hookdeck\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Hookdeck\ApiException;
use Hookdeck\Configuration;
use Hookdeck\FormDataProcessor;
use Hookdeck\HeaderSelector;
use Hookdeck\ObjectSerializer;

/**
 * BulkRetryRequestsApi Class Doc Comment
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BulkRetryRequestsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'cancelRequestBulkRetry' => [
            'application/json',
        ],
        'createRequestBulkRetry' => [
            'application/json',
        ],
        'generateRequestBulkRetryPlan' => [
            'application/json',
        ],
        'getRequestBulkRetries' => [
            'application/json',
        ],
        'getRequestBulkRetry' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation cancelRequestBulkRetry
     *
     * Cancel a requests bulk retry
     *
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hookdeck\Model\BatchOperation|\Hookdeck\Model\APIErrorResponse
     */
    public function cancelRequestBulkRetry($id, string $contentType = self::contentTypes['cancelRequestBulkRetry'][0])
    {
        list($response) = $this->cancelRequestBulkRetryWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation cancelRequestBulkRetryWithHttpInfo
     *
     * Cancel a requests bulk retry
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hookdeck\Model\BatchOperation|\Hookdeck\Model\APIErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function cancelRequestBulkRetryWithHttpInfo($id, string $contentType = self::contentTypes['cancelRequestBulkRetry'][0])
    {
        $request = $this->cancelRequestBulkRetryRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\BatchOperation',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hookdeck\Model\BatchOperation',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\BatchOperation',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation cancelRequestBulkRetryAsync
     *
     * Cancel a requests bulk retry
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelRequestBulkRetryAsync($id, string $contentType = self::contentTypes['cancelRequestBulkRetry'][0])
    {
        return $this->cancelRequestBulkRetryAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation cancelRequestBulkRetryAsyncWithHttpInfo
     *
     * Cancel a requests bulk retry
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelRequestBulkRetryAsyncWithHttpInfo($id, string $contentType = self::contentTypes['cancelRequestBulkRetry'][0])
    {
        $returnType = '\Hookdeck\Model\BatchOperation';
        $request = $this->cancelRequestBulkRetryRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'cancelRequestBulkRetry'
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function cancelRequestBulkRetryRequest($id, string $contentType = self::contentTypes['cancelRequestBulkRetry'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling cancelRequestBulkRetry'
            );
        }


        $resourcePath = '/bulk/requests/retry/{id}/cancel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createRequestBulkRetry
     *
     * Create a requests bulk retry
     *
     * @param  \Hookdeck\Model\CreateRequestBulkRetryRequest $create_request_bulk_retry_request create_request_bulk_retry_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hookdeck\Model\BatchOperation|\Hookdeck\Model\APIErrorResponse|\Hookdeck\Model\APIErrorResponse
     */
    public function createRequestBulkRetry($create_request_bulk_retry_request, string $contentType = self::contentTypes['createRequestBulkRetry'][0])
    {
        list($response) = $this->createRequestBulkRetryWithHttpInfo($create_request_bulk_retry_request, $contentType);
        return $response;
    }

    /**
     * Operation createRequestBulkRetryWithHttpInfo
     *
     * Create a requests bulk retry
     *
     * @param  \Hookdeck\Model\CreateRequestBulkRetryRequest $create_request_bulk_retry_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hookdeck\Model\BatchOperation|\Hookdeck\Model\APIErrorResponse|\Hookdeck\Model\APIErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createRequestBulkRetryWithHttpInfo($create_request_bulk_retry_request, string $contentType = self::contentTypes['createRequestBulkRetry'][0])
    {
        $request = $this->createRequestBulkRetryRequest($create_request_bulk_retry_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\BatchOperation',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hookdeck\Model\BatchOperation',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\BatchOperation',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createRequestBulkRetryAsync
     *
     * Create a requests bulk retry
     *
     * @param  \Hookdeck\Model\CreateRequestBulkRetryRequest $create_request_bulk_retry_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createRequestBulkRetryAsync($create_request_bulk_retry_request, string $contentType = self::contentTypes['createRequestBulkRetry'][0])
    {
        return $this->createRequestBulkRetryAsyncWithHttpInfo($create_request_bulk_retry_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createRequestBulkRetryAsyncWithHttpInfo
     *
     * Create a requests bulk retry
     *
     * @param  \Hookdeck\Model\CreateRequestBulkRetryRequest $create_request_bulk_retry_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createRequestBulkRetryAsyncWithHttpInfo($create_request_bulk_retry_request, string $contentType = self::contentTypes['createRequestBulkRetry'][0])
    {
        $returnType = '\Hookdeck\Model\BatchOperation';
        $request = $this->createRequestBulkRetryRequest($create_request_bulk_retry_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createRequestBulkRetry'
     *
     * @param  \Hookdeck\Model\CreateRequestBulkRetryRequest $create_request_bulk_retry_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createRequestBulkRetryRequest($create_request_bulk_retry_request, string $contentType = self::contentTypes['createRequestBulkRetry'][0])
    {

        // verify the required parameter 'create_request_bulk_retry_request' is set
        if ($create_request_bulk_retry_request === null || (is_array($create_request_bulk_retry_request) && count($create_request_bulk_retry_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_request_bulk_retry_request when calling createRequestBulkRetry'
            );
        }


        $resourcePath = '/bulk/requests/retry';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_request_bulk_retry_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_request_bulk_retry_request));
            } else {
                $httpBody = $create_request_bulk_retry_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation generateRequestBulkRetryPlan
     *
     * Generate a requests bulk retry plan
     *
     * @param  \Hookdeck\Model\CreateRequestBulkRetryRequestQuery|null $query query (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['generateRequestBulkRetryPlan'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hookdeck\Model\GenerateEventBulkRetryPlan200Response|\Hookdeck\Model\APIErrorResponse|\Hookdeck\Model\APIErrorResponse
     */
    public function generateRequestBulkRetryPlan($query = null, string $contentType = self::contentTypes['generateRequestBulkRetryPlan'][0])
    {
        list($response) = $this->generateRequestBulkRetryPlanWithHttpInfo($query, $contentType);
        return $response;
    }

    /**
     * Operation generateRequestBulkRetryPlanWithHttpInfo
     *
     * Generate a requests bulk retry plan
     *
     * @param  \Hookdeck\Model\CreateRequestBulkRetryRequestQuery|null $query (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['generateRequestBulkRetryPlan'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hookdeck\Model\GenerateEventBulkRetryPlan200Response|\Hookdeck\Model\APIErrorResponse|\Hookdeck\Model\APIErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function generateRequestBulkRetryPlanWithHttpInfo($query = null, string $contentType = self::contentTypes['generateRequestBulkRetryPlan'][0])
    {
        $request = $this->generateRequestBulkRetryPlanRequest($query, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\GenerateEventBulkRetryPlan200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hookdeck\Model\GenerateEventBulkRetryPlan200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\GenerateEventBulkRetryPlan200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation generateRequestBulkRetryPlanAsync
     *
     * Generate a requests bulk retry plan
     *
     * @param  \Hookdeck\Model\CreateRequestBulkRetryRequestQuery|null $query (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['generateRequestBulkRetryPlan'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function generateRequestBulkRetryPlanAsync($query = null, string $contentType = self::contentTypes['generateRequestBulkRetryPlan'][0])
    {
        return $this->generateRequestBulkRetryPlanAsyncWithHttpInfo($query, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation generateRequestBulkRetryPlanAsyncWithHttpInfo
     *
     * Generate a requests bulk retry plan
     *
     * @param  \Hookdeck\Model\CreateRequestBulkRetryRequestQuery|null $query (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['generateRequestBulkRetryPlan'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function generateRequestBulkRetryPlanAsyncWithHttpInfo($query = null, string $contentType = self::contentTypes['generateRequestBulkRetryPlan'][0])
    {
        $returnType = '\Hookdeck\Model\GenerateEventBulkRetryPlan200Response';
        $request = $this->generateRequestBulkRetryPlanRequest($query, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'generateRequestBulkRetryPlan'
     *
     * @param  \Hookdeck\Model\CreateRequestBulkRetryRequestQuery|null $query (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['generateRequestBulkRetryPlan'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function generateRequestBulkRetryPlanRequest($query = null, string $contentType = self::contentTypes['generateRequestBulkRetryPlan'][0])
    {



        $resourcePath = '/bulk/requests/retry/plan';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $query,
            'query', // param base name
            'object', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getRequestBulkRetries
     *
     * Get request bulk retries
     *
     * @param  \Hookdeck\Model\GetEventBulkRetriesCancelledAtParameter|null $cancelled_at cancelled_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesCompletedAtParameter|null $completed_at completed_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesCreatedAtParameter|null $created_at created_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesIdParameter|null $id id (optional)
     * @param  bool|null $in_progress in_progress (optional)
     * @param  \Hookdeck\Model\GetRequestBulkRetriesQueryParameter|null $query query (optional)
     * @param  bool|null $query_partial_match query_partial_match (optional)
     * @param  \Hookdeck\Model\GetAttemptsOrderByParameter|null $order_by order_by (optional)
     * @param  \Hookdeck\Model\GetIssueTriggersDirParameter|null $dir dir (optional)
     * @param  int|null $limit limit (optional)
     * @param  string|null $next next (optional)
     * @param  string|null $prev prev (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRequestBulkRetries'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hookdeck\Model\BatchOperationPaginatedResult|\Hookdeck\Model\APIErrorResponse|\Hookdeck\Model\APIErrorResponse
     */
    public function getRequestBulkRetries($cancelled_at = null, $completed_at = null, $created_at = null, $id = null, $in_progress = null, $query = null, $query_partial_match = null, $order_by = null, $dir = null, $limit = null, $next = null, $prev = null, string $contentType = self::contentTypes['getRequestBulkRetries'][0])
    {
        list($response) = $this->getRequestBulkRetriesWithHttpInfo($cancelled_at, $completed_at, $created_at, $id, $in_progress, $query, $query_partial_match, $order_by, $dir, $limit, $next, $prev, $contentType);
        return $response;
    }

    /**
     * Operation getRequestBulkRetriesWithHttpInfo
     *
     * Get request bulk retries
     *
     * @param  \Hookdeck\Model\GetEventBulkRetriesCancelledAtParameter|null $cancelled_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesCompletedAtParameter|null $completed_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesCreatedAtParameter|null $created_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesIdParameter|null $id (optional)
     * @param  bool|null $in_progress (optional)
     * @param  \Hookdeck\Model\GetRequestBulkRetriesQueryParameter|null $query (optional)
     * @param  bool|null $query_partial_match (optional)
     * @param  \Hookdeck\Model\GetAttemptsOrderByParameter|null $order_by (optional)
     * @param  \Hookdeck\Model\GetIssueTriggersDirParameter|null $dir (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $next (optional)
     * @param  string|null $prev (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRequestBulkRetries'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hookdeck\Model\BatchOperationPaginatedResult|\Hookdeck\Model\APIErrorResponse|\Hookdeck\Model\APIErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRequestBulkRetriesWithHttpInfo($cancelled_at = null, $completed_at = null, $created_at = null, $id = null, $in_progress = null, $query = null, $query_partial_match = null, $order_by = null, $dir = null, $limit = null, $next = null, $prev = null, string $contentType = self::contentTypes['getRequestBulkRetries'][0])
    {
        $request = $this->getRequestBulkRetriesRequest($cancelled_at, $completed_at, $created_at, $id, $in_progress, $query, $query_partial_match, $order_by, $dir, $limit, $next, $prev, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\BatchOperationPaginatedResult',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hookdeck\Model\BatchOperationPaginatedResult',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\BatchOperationPaginatedResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getRequestBulkRetriesAsync
     *
     * Get request bulk retries
     *
     * @param  \Hookdeck\Model\GetEventBulkRetriesCancelledAtParameter|null $cancelled_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesCompletedAtParameter|null $completed_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesCreatedAtParameter|null $created_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesIdParameter|null $id (optional)
     * @param  bool|null $in_progress (optional)
     * @param  \Hookdeck\Model\GetRequestBulkRetriesQueryParameter|null $query (optional)
     * @param  bool|null $query_partial_match (optional)
     * @param  \Hookdeck\Model\GetAttemptsOrderByParameter|null $order_by (optional)
     * @param  \Hookdeck\Model\GetIssueTriggersDirParameter|null $dir (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $next (optional)
     * @param  string|null $prev (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRequestBulkRetries'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRequestBulkRetriesAsync($cancelled_at = null, $completed_at = null, $created_at = null, $id = null, $in_progress = null, $query = null, $query_partial_match = null, $order_by = null, $dir = null, $limit = null, $next = null, $prev = null, string $contentType = self::contentTypes['getRequestBulkRetries'][0])
    {
        return $this->getRequestBulkRetriesAsyncWithHttpInfo($cancelled_at, $completed_at, $created_at, $id, $in_progress, $query, $query_partial_match, $order_by, $dir, $limit, $next, $prev, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getRequestBulkRetriesAsyncWithHttpInfo
     *
     * Get request bulk retries
     *
     * @param  \Hookdeck\Model\GetEventBulkRetriesCancelledAtParameter|null $cancelled_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesCompletedAtParameter|null $completed_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesCreatedAtParameter|null $created_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesIdParameter|null $id (optional)
     * @param  bool|null $in_progress (optional)
     * @param  \Hookdeck\Model\GetRequestBulkRetriesQueryParameter|null $query (optional)
     * @param  bool|null $query_partial_match (optional)
     * @param  \Hookdeck\Model\GetAttemptsOrderByParameter|null $order_by (optional)
     * @param  \Hookdeck\Model\GetIssueTriggersDirParameter|null $dir (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $next (optional)
     * @param  string|null $prev (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRequestBulkRetries'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRequestBulkRetriesAsyncWithHttpInfo($cancelled_at = null, $completed_at = null, $created_at = null, $id = null, $in_progress = null, $query = null, $query_partial_match = null, $order_by = null, $dir = null, $limit = null, $next = null, $prev = null, string $contentType = self::contentTypes['getRequestBulkRetries'][0])
    {
        $returnType = '\Hookdeck\Model\BatchOperationPaginatedResult';
        $request = $this->getRequestBulkRetriesRequest($cancelled_at, $completed_at, $created_at, $id, $in_progress, $query, $query_partial_match, $order_by, $dir, $limit, $next, $prev, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getRequestBulkRetries'
     *
     * @param  \Hookdeck\Model\GetEventBulkRetriesCancelledAtParameter|null $cancelled_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesCompletedAtParameter|null $completed_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesCreatedAtParameter|null $created_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesIdParameter|null $id (optional)
     * @param  bool|null $in_progress (optional)
     * @param  \Hookdeck\Model\GetRequestBulkRetriesQueryParameter|null $query (optional)
     * @param  bool|null $query_partial_match (optional)
     * @param  \Hookdeck\Model\GetAttemptsOrderByParameter|null $order_by (optional)
     * @param  \Hookdeck\Model\GetIssueTriggersDirParameter|null $dir (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $next (optional)
     * @param  string|null $prev (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRequestBulkRetries'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRequestBulkRetriesRequest($cancelled_at = null, $completed_at = null, $created_at = null, $id = null, $in_progress = null, $query = null, $query_partial_match = null, $order_by = null, $dir = null, $limit = null, $next = null, $prev = null, string $contentType = self::contentTypes['getRequestBulkRetries'][0])
    {










        if ($limit !== null && $limit > 255) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling BulkRetryRequestsApi.getRequestBulkRetries, must be smaller than or equal to 255.');
        }
        if ($limit !== null && $limit < 0) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling BulkRetryRequestsApi.getRequestBulkRetries, must be bigger than or equal to 0.');
        }
        
        if ($next !== null && strlen($next) > 255) {
            throw new \InvalidArgumentException('invalid length for "$next" when calling BulkRetryRequestsApi.getRequestBulkRetries, must be smaller than or equal to 255.');
        }
        
        if ($prev !== null && strlen($prev) > 255) {
            throw new \InvalidArgumentException('invalid length for "$prev" when calling BulkRetryRequestsApi.getRequestBulkRetries, must be smaller than or equal to 255.');
        }
        

        $resourcePath = '/bulk/requests/retry';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cancelled_at,
            'cancelled_at', // param base name
            'anyOf&lt;DateTime,Operators&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $completed_at,
            'completed_at', // param base name
            'anyOf&lt;DateTime,Operators&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $created_at,
            'created_at', // param base name
            'anyOf&lt;DateTime,Operators&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $id,
            'id', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $in_progress,
            'in_progress', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $query,
            'query', // param base name
            'object', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $query_partial_match,
            'query_partial_match', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order_by,
            'order_by', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $dir,
            'dir', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $next,
            'next', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $prev,
            'prev', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getRequestBulkRetry
     *
     * Get a requests bulk retry
     *
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hookdeck\Model\BatchOperation|\Hookdeck\Model\APIErrorResponse
     */
    public function getRequestBulkRetry($id, string $contentType = self::contentTypes['getRequestBulkRetry'][0])
    {
        list($response) = $this->getRequestBulkRetryWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getRequestBulkRetryWithHttpInfo
     *
     * Get a requests bulk retry
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hookdeck\Model\BatchOperation|\Hookdeck\Model\APIErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRequestBulkRetryWithHttpInfo($id, string $contentType = self::contentTypes['getRequestBulkRetry'][0])
    {
        $request = $this->getRequestBulkRetryRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\BatchOperation',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hookdeck\Model\BatchOperation',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\BatchOperation',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getRequestBulkRetryAsync
     *
     * Get a requests bulk retry
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRequestBulkRetryAsync($id, string $contentType = self::contentTypes['getRequestBulkRetry'][0])
    {
        return $this->getRequestBulkRetryAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getRequestBulkRetryAsyncWithHttpInfo
     *
     * Get a requests bulk retry
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRequestBulkRetryAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getRequestBulkRetry'][0])
    {
        $returnType = '\Hookdeck\Model\BatchOperation';
        $request = $this->getRequestBulkRetryRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getRequestBulkRetry'
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRequestBulkRetry'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRequestBulkRetryRequest($id, string $contentType = self::contentTypes['getRequestBulkRetry'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getRequestBulkRetry'
            );
        }


        $resourcePath = '/bulk/requests/retry/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
