<?php
/**
 * EventsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hookdeck\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Hookdeck\ApiException;
use Hookdeck\Configuration;
use Hookdeck\FormDataProcessor;
use Hookdeck\HeaderSelector;
use Hookdeck\ObjectSerializer;

/**
 * EventsApi Class Doc Comment
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getEvent' => [
            'application/json',
        ],
        'getEventRawBody' => [
            'application/json',
        ],
        'getEvents' => [
            'application/json',
        ],
        'muteEvent' => [
            'application/json',
        ],
        'retryEvent' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getEvent
     *
     * Get an event
     *
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvent'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hookdeck\Model\Event|\Hookdeck\Model\APIErrorResponse
     */
    public function getEvent($id, string $contentType = self::contentTypes['getEvent'][0])
    {
        list($response) = $this->getEventWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getEventWithHttpInfo
     *
     * Get an event
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvent'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hookdeck\Model\Event|\Hookdeck\Model\APIErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEventWithHttpInfo($id, string $contentType = self::contentTypes['getEvent'][0])
    {
        $request = $this->getEventRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\Event',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hookdeck\Model\Event',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\Event',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getEventAsync
     *
     * Get an event
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEventAsync($id, string $contentType = self::contentTypes['getEvent'][0])
    {
        return $this->getEventAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEventAsyncWithHttpInfo
     *
     * Get an event
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEventAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getEvent'][0])
    {
        $returnType = '\Hookdeck\Model\Event';
        $request = $this->getEventRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEvent'
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getEventRequest($id, string $contentType = self::contentTypes['getEvent'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getEvent'
            );
        }


        $resourcePath = '/events/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getEventRawBody
     *
     * Get a event raw body data
     *
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEventRawBody'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hookdeck\Model\RawBody|\Hookdeck\Model\APIErrorResponse
     */
    public function getEventRawBody($id, string $contentType = self::contentTypes['getEventRawBody'][0])
    {
        list($response) = $this->getEventRawBodyWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getEventRawBodyWithHttpInfo
     *
     * Get a event raw body data
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEventRawBody'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hookdeck\Model\RawBody|\Hookdeck\Model\APIErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEventRawBodyWithHttpInfo($id, string $contentType = self::contentTypes['getEventRawBody'][0])
    {
        $request = $this->getEventRawBodyRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\RawBody',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hookdeck\Model\RawBody',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\RawBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getEventRawBodyAsync
     *
     * Get a event raw body data
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEventRawBody'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEventRawBodyAsync($id, string $contentType = self::contentTypes['getEventRawBody'][0])
    {
        return $this->getEventRawBodyAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEventRawBodyAsyncWithHttpInfo
     *
     * Get a event raw body data
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEventRawBody'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEventRawBodyAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getEventRawBody'][0])
    {
        $returnType = '\Hookdeck\Model\RawBody';
        $request = $this->getEventRawBodyRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEventRawBody'
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEventRawBody'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getEventRawBodyRequest($id, string $contentType = self::contentTypes['getEventRawBody'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getEventRawBody'
            );
        }


        $resourcePath = '/events/{id}/raw_body';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getEvents
     *
     * Get events
     *
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterId|null $id id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterStatus|null $status status (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterWebhookId|null $webhook_id webhook_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterDestinationId|null $destination_id destination_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterSourceId|null $source_id source_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterAttempts|null $attempts attempts (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterResponseStatus|null $response_status response_status (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterSuccessfulAt|null $successful_at successful_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCreatedAt|null $created_at created_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterErrorCode|null $error_code error_code (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCliId|null $cli_id cli_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterLastAttemptAt|null $last_attempt_at last_attempt_at (optional)
     * @param  string|null $search_term search_term (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterHeaders|null $headers headers (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterBody|null $body body (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterParsedQuery|null $parsed_query parsed_query (optional)
     * @param  string|null $path path (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCliUserId|null $cli_user_id cli_user_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $issue_id issue_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $event_data_id event_data_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $bulk_retry_id bulk_retry_id (optional)
     * @param  string|null $include include (optional)
     * @param  string|null $order_by order_by (optional)
     * @param  string|null $dir dir (optional)
     * @param  int|null $limit limit (optional)
     * @param  string|null $next next (optional)
     * @param  string|null $prev prev (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvents'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hookdeck\Model\EventPaginatedResult|\Hookdeck\Model\APIErrorResponse|\Hookdeck\Model\APIErrorResponse
     */
    public function getEvents($id = null, $status = null, $webhook_id = null, $destination_id = null, $source_id = null, $attempts = null, $response_status = null, $successful_at = null, $created_at = null, $error_code = null, $cli_id = null, $last_attempt_at = null, $search_term = null, $headers = null, $body = null, $parsed_query = null, $path = null, $cli_user_id = null, $issue_id = null, $event_data_id = null, $bulk_retry_id = null, $include = null, $order_by = null, $dir = null, $limit = null, $next = null, $prev = null, string $contentType = self::contentTypes['getEvents'][0])
    {
        list($response) = $this->getEventsWithHttpInfo($id, $status, $webhook_id, $destination_id, $source_id, $attempts, $response_status, $successful_at, $created_at, $error_code, $cli_id, $last_attempt_at, $search_term, $headers, $body, $parsed_query, $path, $cli_user_id, $issue_id, $event_data_id, $bulk_retry_id, $include, $order_by, $dir, $limit, $next, $prev, $contentType);
        return $response;
    }

    /**
     * Operation getEventsWithHttpInfo
     *
     * Get events
     *
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterId|null $id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterStatus|null $status (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterWebhookId|null $webhook_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterDestinationId|null $destination_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterSourceId|null $source_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterAttempts|null $attempts (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterResponseStatus|null $response_status (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterSuccessfulAt|null $successful_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCreatedAt|null $created_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterErrorCode|null $error_code (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCliId|null $cli_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterLastAttemptAt|null $last_attempt_at (optional)
     * @param  string|null $search_term (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterHeaders|null $headers (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterBody|null $body (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterParsedQuery|null $parsed_query (optional)
     * @param  string|null $path (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCliUserId|null $cli_user_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $issue_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $event_data_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $bulk_retry_id (optional)
     * @param  string|null $include (optional)
     * @param  string|null $order_by (optional)
     * @param  string|null $dir (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $next (optional)
     * @param  string|null $prev (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvents'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hookdeck\Model\EventPaginatedResult|\Hookdeck\Model\APIErrorResponse|\Hookdeck\Model\APIErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEventsWithHttpInfo($id = null, $status = null, $webhook_id = null, $destination_id = null, $source_id = null, $attempts = null, $response_status = null, $successful_at = null, $created_at = null, $error_code = null, $cli_id = null, $last_attempt_at = null, $search_term = null, $headers = null, $body = null, $parsed_query = null, $path = null, $cli_user_id = null, $issue_id = null, $event_data_id = null, $bulk_retry_id = null, $include = null, $order_by = null, $dir = null, $limit = null, $next = null, $prev = null, string $contentType = self::contentTypes['getEvents'][0])
    {
        $request = $this->getEventsRequest($id, $status, $webhook_id, $destination_id, $source_id, $attempts, $response_status, $successful_at, $created_at, $error_code, $cli_id, $last_attempt_at, $search_term, $headers, $body, $parsed_query, $path, $cli_user_id, $issue_id, $event_data_id, $bulk_retry_id, $include, $order_by, $dir, $limit, $next, $prev, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\EventPaginatedResult',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hookdeck\Model\EventPaginatedResult',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\EventPaginatedResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getEventsAsync
     *
     * Get events
     *
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterId|null $id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterStatus|null $status (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterWebhookId|null $webhook_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterDestinationId|null $destination_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterSourceId|null $source_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterAttempts|null $attempts (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterResponseStatus|null $response_status (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterSuccessfulAt|null $successful_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCreatedAt|null $created_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterErrorCode|null $error_code (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCliId|null $cli_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterLastAttemptAt|null $last_attempt_at (optional)
     * @param  string|null $search_term (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterHeaders|null $headers (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterBody|null $body (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterParsedQuery|null $parsed_query (optional)
     * @param  string|null $path (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCliUserId|null $cli_user_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $issue_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $event_data_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $bulk_retry_id (optional)
     * @param  string|null $include (optional)
     * @param  string|null $order_by (optional)
     * @param  string|null $dir (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $next (optional)
     * @param  string|null $prev (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvents'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEventsAsync($id = null, $status = null, $webhook_id = null, $destination_id = null, $source_id = null, $attempts = null, $response_status = null, $successful_at = null, $created_at = null, $error_code = null, $cli_id = null, $last_attempt_at = null, $search_term = null, $headers = null, $body = null, $parsed_query = null, $path = null, $cli_user_id = null, $issue_id = null, $event_data_id = null, $bulk_retry_id = null, $include = null, $order_by = null, $dir = null, $limit = null, $next = null, $prev = null, string $contentType = self::contentTypes['getEvents'][0])
    {
        return $this->getEventsAsyncWithHttpInfo($id, $status, $webhook_id, $destination_id, $source_id, $attempts, $response_status, $successful_at, $created_at, $error_code, $cli_id, $last_attempt_at, $search_term, $headers, $body, $parsed_query, $path, $cli_user_id, $issue_id, $event_data_id, $bulk_retry_id, $include, $order_by, $dir, $limit, $next, $prev, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEventsAsyncWithHttpInfo
     *
     * Get events
     *
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterId|null $id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterStatus|null $status (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterWebhookId|null $webhook_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterDestinationId|null $destination_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterSourceId|null $source_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterAttempts|null $attempts (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterResponseStatus|null $response_status (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterSuccessfulAt|null $successful_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCreatedAt|null $created_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterErrorCode|null $error_code (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCliId|null $cli_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterLastAttemptAt|null $last_attempt_at (optional)
     * @param  string|null $search_term (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterHeaders|null $headers (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterBody|null $body (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterParsedQuery|null $parsed_query (optional)
     * @param  string|null $path (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCliUserId|null $cli_user_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $issue_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $event_data_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $bulk_retry_id (optional)
     * @param  string|null $include (optional)
     * @param  string|null $order_by (optional)
     * @param  string|null $dir (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $next (optional)
     * @param  string|null $prev (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvents'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEventsAsyncWithHttpInfo($id = null, $status = null, $webhook_id = null, $destination_id = null, $source_id = null, $attempts = null, $response_status = null, $successful_at = null, $created_at = null, $error_code = null, $cli_id = null, $last_attempt_at = null, $search_term = null, $headers = null, $body = null, $parsed_query = null, $path = null, $cli_user_id = null, $issue_id = null, $event_data_id = null, $bulk_retry_id = null, $include = null, $order_by = null, $dir = null, $limit = null, $next = null, $prev = null, string $contentType = self::contentTypes['getEvents'][0])
    {
        $returnType = '\Hookdeck\Model\EventPaginatedResult';
        $request = $this->getEventsRequest($id, $status, $webhook_id, $destination_id, $source_id, $attempts, $response_status, $successful_at, $created_at, $error_code, $cli_id, $last_attempt_at, $search_term, $headers, $body, $parsed_query, $path, $cli_user_id, $issue_id, $event_data_id, $bulk_retry_id, $include, $order_by, $dir, $limit, $next, $prev, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEvents'
     *
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterId|null $id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterStatus|null $status (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterWebhookId|null $webhook_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterDestinationId|null $destination_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterSourceId|null $source_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterAttempts|null $attempts (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterResponseStatus|null $response_status (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterSuccessfulAt|null $successful_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCreatedAt|null $created_at (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterErrorCode|null $error_code (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCliId|null $cli_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterLastAttemptAt|null $last_attempt_at (optional)
     * @param  string|null $search_term (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterHeaders|null $headers (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterBody|null $body (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterParsedQuery|null $parsed_query (optional)
     * @param  string|null $path (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterCliUserId|null $cli_user_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $issue_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $event_data_id (optional)
     * @param  \Hookdeck\Model\GetEventBulkRetriesQueryParameterIssueId|null $bulk_retry_id (optional)
     * @param  string|null $include (optional)
     * @param  string|null $order_by (optional)
     * @param  string|null $dir (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $next (optional)
     * @param  string|null $prev (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvents'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getEventsRequest($id = null, $status = null, $webhook_id = null, $destination_id = null, $source_id = null, $attempts = null, $response_status = null, $successful_at = null, $created_at = null, $error_code = null, $cli_id = null, $last_attempt_at = null, $search_term = null, $headers = null, $body = null, $parsed_query = null, $path = null, $cli_user_id = null, $issue_id = null, $event_data_id = null, $bulk_retry_id = null, $include = null, $order_by = null, $dir = null, $limit = null, $next = null, $prev = null, string $contentType = self::contentTypes['getEvents'][0])
    {













        if ($search_term !== null && strlen($search_term) < 3) {
            throw new \InvalidArgumentException('invalid length for "$search_term" when calling EventsApi.getEvents, must be bigger than or equal to 3.');
        }
        









        if ($order_by !== null && strlen($order_by) > 255) {
            throw new \InvalidArgumentException('invalid length for "$order_by" when calling EventsApi.getEvents, must be smaller than or equal to 255.');
        }
        

        if ($limit !== null && $limit > 255) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling EventsApi.getEvents, must be smaller than or equal to 255.');
        }
        if ($limit !== null && $limit < 0) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling EventsApi.getEvents, must be bigger than or equal to 0.');
        }
        
        if ($next !== null && strlen($next) > 255) {
            throw new \InvalidArgumentException('invalid length for "$next" when calling EventsApi.getEvents, must be smaller than or equal to 255.');
        }
        
        if ($prev !== null && strlen($prev) > 255) {
            throw new \InvalidArgumentException('invalid length for "$prev" when calling EventsApi.getEvents, must be smaller than or equal to 255.');
        }
        

        $resourcePath = '/events';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $id,
            'id', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'anyOf&lt;EventStatus,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $webhook_id,
            'webhook_id', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $destination_id,
            'destination_id', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $source_id,
            'source_id', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $attempts,
            'attempts', // param base name
            'anyOf&lt;integer,Operators&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $response_status,
            'response_status', // param base name
            'anyOf&lt;integer,Operators,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $successful_at,
            'successful_at', // param base name
            'anyOf&lt;DateTime,Operators&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $created_at,
            'created_at', // param base name
            'anyOf&lt;DateTime,Operators&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $error_code,
            'error_code', // param base name
            'anyOf&lt;AttemptErrorCodes,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cli_id,
            'cli_id', // param base name
            'anyOf&lt;string,getEventBulkRetries_query_parameter_cli_id_anyOf,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $last_attempt_at,
            'last_attempt_at', // param base name
            'anyOf&lt;DateTime,Operators&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search_term,
            'search_term', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $headers,
            'headers', // param base name
            'anyOf&lt;string,object&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $body,
            'body', // param base name
            'anyOf&lt;string,object&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $parsed_query,
            'parsed_query', // param base name
            'anyOf&lt;string,object&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $path,
            'path', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cli_user_id,
            'cli_user_id', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $issue_id,
            'issue_id', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $event_data_id,
            'event_data_id', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $bulk_retry_id,
            'bulk_retry_id', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include,
            'include', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order_by,
            'order_by', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $dir,
            'dir', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $next,
            'next', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $prev,
            'prev', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation muteEvent
     *
     * Mute an event
     *
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['muteEvent'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hookdeck\Model\Event|\Hookdeck\Model\APIErrorResponse
     */
    public function muteEvent($id, string $contentType = self::contentTypes['muteEvent'][0])
    {
        list($response) = $this->muteEventWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation muteEventWithHttpInfo
     *
     * Mute an event
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['muteEvent'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hookdeck\Model\Event|\Hookdeck\Model\APIErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function muteEventWithHttpInfo($id, string $contentType = self::contentTypes['muteEvent'][0])
    {
        $request = $this->muteEventRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\Event',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hookdeck\Model\Event',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\Event',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation muteEventAsync
     *
     * Mute an event
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['muteEvent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function muteEventAsync($id, string $contentType = self::contentTypes['muteEvent'][0])
    {
        return $this->muteEventAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation muteEventAsyncWithHttpInfo
     *
     * Mute an event
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['muteEvent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function muteEventAsyncWithHttpInfo($id, string $contentType = self::contentTypes['muteEvent'][0])
    {
        $returnType = '\Hookdeck\Model\Event';
        $request = $this->muteEventRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'muteEvent'
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['muteEvent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function muteEventRequest($id, string $contentType = self::contentTypes['muteEvent'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling muteEvent'
            );
        }


        $resourcePath = '/events/{id}/mute';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation retryEvent
     *
     * Retry an event
     *
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['retryEvent'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hookdeck\Model\RetriedEvent|\Hookdeck\Model\APIErrorResponse
     */
    public function retryEvent($id, string $contentType = self::contentTypes['retryEvent'][0])
    {
        list($response) = $this->retryEventWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation retryEventWithHttpInfo
     *
     * Retry an event
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['retryEvent'] to see the possible values for this operation
     *
     * @throws \Hookdeck\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hookdeck\Model\RetriedEvent|\Hookdeck\Model\APIErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function retryEventWithHttpInfo($id, string $contentType = self::contentTypes['retryEvent'][0])
    {
        $request = $this->retryEventRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\RetriedEvent',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Hookdeck\Model\APIErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hookdeck\Model\RetriedEvent',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\RetriedEvent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hookdeck\Model\APIErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation retryEventAsync
     *
     * Retry an event
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['retryEvent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function retryEventAsync($id, string $contentType = self::contentTypes['retryEvent'][0])
    {
        return $this->retryEventAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation retryEventAsyncWithHttpInfo
     *
     * Retry an event
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['retryEvent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function retryEventAsyncWithHttpInfo($id, string $contentType = self::contentTypes['retryEvent'][0])
    {
        $returnType = '\Hookdeck\Model\RetriedEvent';
        $request = $this->retryEventRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'retryEvent'
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['retryEvent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function retryEventRequest($id, string $contentType = self::contentTypes['retryEvent'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling retryEvent'
            );
        }


        $resourcePath = '/events/{id}/retry';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
