<?php
/**
 * BulkRetryEventsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Hookdeck\Test\Api;

use \Hookdeck\Configuration;
use \Hookdeck\ApiException;
use \Hookdeck\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BulkRetryEventsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BulkRetryEventsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelEventBulkRetry
     *
     * Cancel an events bulk retry.
     *
     */
    public function testCancelEventBulkRetry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createEventBulkRetry
     *
     * Create an events bulk retry.
     *
     */
    public function testCreateEventBulkRetry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateEventBulkRetryPlan
     *
     * Generate an events bulk retry plan.
     *
     */
    public function testGenerateEventBulkRetryPlan()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEventBulkRetries
     *
     * Get events bulk retries.
     *
     */
    public function testGetEventBulkRetries()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEventBulkRetry
     *
     * Get an events bulk retry.
     *
     */
    public function testGetEventBulkRetry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
