<?php
/**
 * DestinationsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Hookdeck\Test\Api;

use \Hookdeck\Configuration;
use \Hookdeck\ApiException;
use \Hookdeck\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DestinationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createDestination
     *
     * Create a destination.
     *
     */
    public function testCreateDestination()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteDestination
     *
     * Delete a destination.
     *
     */
    public function testDeleteDestination()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for disableDestination
     *
     * Disable a destination.
     *
     */
    public function testDisableDestination()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for disableDestinationArchive
     *
     * Disable a destination.
     *
     */
    public function testDisableDestinationArchive()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for enableDestination
     *
     * Enable a destination.
     *
     */
    public function testEnableDestination()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for enableDestinationUnarchive
     *
     * Enable a destination.
     *
     */
    public function testEnableDestinationUnarchive()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDestination
     *
     * Get a destination.
     *
     */
    public function testGetDestination()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDestinations
     *
     * Get destinations.
     *
     */
    public function testGetDestinations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDestination
     *
     * Update a destination.
     *
     */
    public function testUpdateDestination()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for upsertDestination
     *
     * Update or create a destination.
     *
     */
    public function testUpsertDestination()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
