<?php
/**
 * RequestsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Hookdeck\Test\Api;

use \Hookdeck\Configuration;
use \Hookdeck\ApiException;
use \Hookdeck\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RequestsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RequestsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getRequest
     *
     * Get a request.
     *
     */
    public function testGetRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRequestEvents
     *
     * Get request events.
     *
     */
    public function testGetRequestEvents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRequestIgnoredEvents
     *
     * Get request ignored events.
     *
     */
    public function testGetRequestIgnoredEvents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRequestRawBody
     *
     * Get a request raw body data.
     *
     */
    public function testGetRequestRawBody()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRequests
     *
     * Get requests.
     *
     */
    public function testGetRequests()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retryRequest
     *
     * Retry a request.
     *
     */
    public function testRetryRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
