<?php
/**
 * SourcesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Hookdeck\Test\Api;

use \Hookdeck\Configuration;
use \Hookdeck\ApiException;
use \Hookdeck\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SourcesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SourcesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createSource
     *
     * Create a source.
     *
     */
    public function testCreateSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSource
     *
     * Delete a source.
     *
     */
    public function testDeleteSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for disableSource
     *
     * Disable a source.
     *
     */
    public function testDisableSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for disableSourceArchive
     *
     * Disable a source.
     *
     */
    public function testDisableSourceArchive()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for enableSource
     *
     * Enable a source.
     *
     */
    public function testEnableSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for enableSourceUnarchive
     *
     * Enable a source.
     *
     */
    public function testEnableSourceUnarchive()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSource
     *
     * Get a source.
     *
     */
    public function testGetSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSources
     *
     * Get sources.
     *
     */
    public function testGetSources()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSource
     *
     * Update a source.
     *
     */
    public function testUpdateSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for upsertSource
     *
     * Update or create a source.
     *
     */
    public function testUpsertSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
