<?php
/**
 * SourceTypeConfigTREEZORTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hookdeck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hookdeck Admin REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@hookdeck.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Hookdeck\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SourceTypeConfigTREEZORTest Class Doc Comment
 *
 * @category    Class
 * @description The type config for TREEZOR. Requires type to be &#x60;TREEZOR&#x60;.
 * @package     Hookdeck
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SourceTypeConfigTREEZORTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SourceTypeConfigTREEZOR"
     */
    public function testSourceTypeConfigTREEZOR()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "auth"
     */
    public function testPropertyAuth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
